Support HuggingFace Transformers
raznem/parsera pull request #12
Opened 2024-08-19 17:11 UTC by SamTheCoder777

This PR introduces support for HuggingFace Transformers by adding a new class, `ParseraHuggingFace`. The class is designed for lazy loading, ensuring that users only install the `transformers` library if they choose to use it.

List of changes:

- **Added:** `ParseraHuggingFace` class for HuggingFace integration.
- **Added:** custom `HuggingFaceModel` in `model.py`
- **Updated:** `README` with examples for using `ParseraHuggingFace`

2024-08-20 00:37 UTC, portoaj commented
I think this a great feature but I think making a whole new ParseraHuggingFace is unnecessary unless there's something that I'm missing. I think it would be better if you could either make the ParseraHuggingFace class inherit _run, run, and arun from Parsera since those seem to be mostly untouched, or even better just add the HuggingFace support to the existing Parsera class potentially with some helper methods.

2024-08-20 08:34 UTC, raznem requested changes
Thanks for the contribution, hugging face is worth implementing!
Agree with @portoaj, `ParseraHuggingFace` duplicates the code of `Parsera`.
The cleanest way to do it would be to simply support `HuggingFaceModel` since it's already a `BaseChatModel` instance.

2024-08-20 18:42 UTC, SamTheCoder777 commented
I’ve removed the unnecessary `ParseraHuggingFace` class to avoid code duplication. Now, `HuggingFaceModel` integrates directly with `Parsera` as it's already a `BaseChatModel` instance.

2024-08-21 11:33 UTC, raznem approved these changes

2024-08-21 11:35 UTC, merged