Add CLI and Docker support
raznem/parsera pull request #17
Opened 2024-09-08 17:38 UTC by danyathecoder

Add Table of contests.
Add documentations for Docker usage.
Add Docker support.
Add CLI support.

2024-09-09 14:35 UTC, raznem requested changes

2024-09-09 14:35 UTC, raznem commented on README.md
CLI Works well, but when I have issues with docker. When I am running it with `make up` it fails with an error:
```
ERROR: for parsera  Cannot start service parsera: failed to create shim: OCI runtime create failed: 
container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: 
rootfs_linux.go:75: mounting "/Users/mishazanka/projects/scrapping/parsera/scheme.json" to rootfs at "/app/
scheme.json" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a
file (or vice-versa)? Check if the specified host path exists and is the expected type
```
It seems like it's trying to create `scheme.json` folder, cause when there is no `scheme.json` file, such a folder is created.

2024-09-09 14:38 UTC, raznem commented on README.md
Also, I couldn't find output.json after docker is run.

2024-09-11 14:42 UTC, danyathecoder commented on README.md
It looks like the container didn't start or even build, are you sure, that the docker agent is working on your system?

2024-09-13 10:26 UTC, raznem approved these changes

2024-09-13 10:26 UTC, merged